# -*- coding: utf-8 -*-
''' @author: Daniel Dreke (Fraunhofer ISI, CC X) '''

COUNTRIES = \
    [   # http://en.wikipedia.org/wiki/ISO_3166-1
        (40, 'AT', 'Austria', 'Österreich','aut', 1)
        , (56, 'BE', 'Belgium', 'Belgien','bel', 1)
        , (100, 'BG', 'Bulgaria', 'Bulgarien','bgr', 1)
        , (191, 'HR', 'Croatia', 'Kroatien','hrv', 1)
        , (196, 'CY', 'Cyprus', 'Zypern','cyp', 1)
        , (203, 'CZ', 'Czech Republic', 'Tschechische Republik','cze', 1)
        , (208, 'DK', 'Denmark', 'Dänemark','dnk', 1)
        , (233, 'EE', 'Estonia', 'Estland','est', 1)
        , (246, 'FI', 'Finland', 'Finnland','fin', 1)
        , (250, 'FR', 'France', 'Frankreich','fra', 1)
        , (276, 'DE', 'Germany', 'Deutschland','deu', 1)
        , (300, 'GR', 'Greece', 'Griechenland','grc', 1)
        , (348, 'HU', 'Hungary', 'Ungarn','hun', 1)
        , (352, 'IS', 'Iceland', 'Island','isl', 1)
        , (372, 'IE', 'Ireland', 'Irland','irl', 1)
        , (380, 'IT', 'Italy', 'Italien','ita', 1)
        , (428, 'LV', 'Latvia', 'Lettland','lva', 1)
        , (440, 'LT', 'Lithuania', 'Litauen','ltu', 1)
        , (442, 'LU', 'Luxembourg', 'Luxemburg','lux', 1)
        , (470, 'MT', 'Malta', 'Malta','mlt', 1)
        , (528, 'NL', 'Netherlands', 'Niederlande','nld', 1)
        , (578, 'NO', 'Norway', 'Norwegen','nor', 1)
        , (616, 'PL', 'Poland', 'Polen','pol', 1)
        , (620, 'PT', 'Portugal', 'Portugal','prt', 1)
        , (642, 'RO', 'Romania', 'Rumänien','rou', 1)
        , (688, 'RS', 'Serbia', 'Serbien','srb', 1)
        , (703, 'SK', 'Slovakia', 'Slowakei','svk', 1)
        , (705, 'SI', 'Slovenia', 'Slowenien','svn', 1)
        , (724, 'ES', 'Spain', 'Spanien','esp', 1)
        , (752, 'SE', 'Sweden', 'Schweden','swe', 1)
        , (756, 'CH', 'Switzerland', 'Schweiz (Confoederatio Helvetica)', 'che', 1)
        , (826, 'GB', 'United Kingdom', 'Vereinigtes Königreich Großbritannien und Nordirland','gbr', 1)
        , (900, 'VI', 'Vienna', 'WIEN','vie', 1)
        , (4, 'AF', 'Afghanistan', 'Afghanistan','afg', 0)
        , (8, 'AL', 'Albania', 'Albanien','alb', 0)
        , (248, 'AX', 'Åland Islands', 'Åland','ala', 0)
        , (12, 'DZ', 'Algeria', 'Algerien','dza', 0)
        , (16, 'AS', 'American Samoa', 'Amerikanisch-Samoa','asm', 0)
        , (20, 'AD', 'Andorra', 'Andorra','and', 0)
        , (24, 'AO', 'Angola', 'Angola','ago', 0)
        , (660, 'AI', 'Anguilla', 'Anguilla','aia', 0)
        , (10, 'AQ', 'Antarctica', 'Antarktika','ata', 0)
        , (28, 'AG', 'Antigua and Barbuda', 'Antigua und Barbuda','atg', 0)
        , (32, 'AR', 'Argentina', 'Argentinien','arg', 0)
        , (51, 'AM', 'Armenia', 'Armenien','arm', 0)
        , (533, 'AW', 'Aruba', 'Aruba','abw', 0)
        , (36, 'AU', 'Australia', 'Australien','aus', 0)
        , (31, 'AZ', 'Azerbaijan', 'Aserbaidschan','aze', 0)
        , (44, 'BS', 'Bahamas', 'Bahamas','bhs', 0)
        , (48, 'BH', 'Bahrain', 'Bahrain','bhr', 0)
        , (50, 'BD', 'Bangladesh', 'Bangladesch','bgd', 0)
        , (52, 'BB', 'Barbados', 'Barbados','brb', 0)
        , (112, 'BY', 'Belarus', 'Belarus (Weißrussland)','blr', 0)
        , (84, 'BZ', 'Belize', 'Belize','blz', 0)
        , (204, 'BJ', 'Benin', 'Benin','ben', 0)
        , (60, 'BM', 'Bermuda', 'Bermuda','bmu', 0)
        , (64, 'BT', 'Bhutan', 'Bhutan','btn', 0)
        , (68, 'BO', 'Bolivia, Plurinational State of', 'Bolivien','bol', 0)
        , (535, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba (Niederlande)','bes', 0)
        , (70, 'BA', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina','bih', 0)
        , (72, 'BW', 'Botswana', 'Botswana','bwa', 0)
        , (74, 'BV', 'Bouvet Island', 'Bouvetinsel','bvt', 0)
        , (76, 'BR', 'Brazil', 'Brasilien','bra', 0)
        , (86, 'IO', 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean','iot', 0)
        , (96, 'BN', 'Brunei Darussalam', 'Brunei Darussalam','brn', 0)
        , (854, 'BF', 'Burkina Faso', 'Burkina Faso','bfa', 0)
        , (108, 'BI', 'Burundi', 'Burundi','bdi', 0)
        , (116, 'KH', 'Cambodia', 'Kambodscha','khm', 0)
        , (120, 'CM', 'Cameroon', 'Kamerun','cmr', 0)
        , (124, 'CA', 'Canada', 'Kanada','can', 0)
        , (132, 'CV', 'Cape Verde', 'Kap Verde','cpv', 0)
        , (136, 'KY', 'Cayman Islands', 'Kaimaninseln','cym', 0)
        , (140, 'CF', 'Central African Republic', 'Zentralafrikanische Republik','caf', 0)
        , (148, 'TD', 'Chad', 'Tschad','tcd', 0)
        , (152, 'CL', 'Chile', 'Chile','chl', 0)
        , (156, 'CN', 'China', 'China, Volksrepublik','chn', 0)
        , (162, 'CX', 'Christmas Island', 'Weihnachtsinsel','cxr', 0)
        , (166, 'CC', 'Cocos (Keeling)','Kokosinseln','cck', 0)
        , (170, 'CO', 'Colombia', 'Kolumbien','col', 0)
        , (174, 'KM', 'Comoros', 'Komoren','com', 0)
        , (178, 'CG', 'Congo', 'Republik Kongo','cog', 0)
        , (180, 'CD', 'Congo, the Democratic Republic of the', 'Kongo, Demokratische Republik (ehem. Zaire)','cod', 0)
        , (184, 'CK', 'Cook Islands', 'Cookinseln','cok', 0)
        , (188, 'CR', 'Costa Rica', 'Costa Rica','cri', 0)
        , (192, 'CU', 'Cuba', 'Kuba','cub', 0)
        , (531, 'CW', 'Curaçao', 'Curaçao','cuw', 0)
        , (262, 'DJ', 'Djibouti', 'Dschibuti','dji', 0)
        , (212, 'DM', 'Dominica', 'Dominica','dma', 0)
        , (214, 'DO', 'Dominican Republic', 'Dominikanische Republik','dom', 0)
        , (218, 'EC', 'Ecuador', 'Ecuador','ecu', 0)
        , (818, 'EG', 'Egypt', 'Ägypten','egy', 0)
        , (222, 'SV', 'El Salvador', 'El Salvador','slv', 0)
        , (226, 'GQ', 'Equatorial Guinea', 'Äquatorialguinea','gnq', 0)
        , (232, 'ER', 'Eritrea', 'Eritrea','eri', 0)
        , (231, 'ET', 'Ethiopia', 'Äthiopien','eth', 0)
        , (238, 'FK', 'Falkland Islands (Malvinas)', 'Falklandinseln','flk', 0)
        , (234, 'FO', 'Faroe Islands', 'Färöer','fro', 0)
        , (242, 'FJ', 'Fiji', 'Fidschi','fji', 0)
        , (254, 'GF', 'French Guiana', 'Französisch-Guayana','guf', 0)
        , (258, 'PF', 'French Polynesia', 'Französisch-Polynesien','pyf', 0)
        , (260, 'TF', 'French Southern Territories', 'Französische Süd- und Antarktisgebiete','atf', 0)
        , (266, 'GA', 'Gabon', 'Gabun','gab', 0)
        , (270, 'GM', 'Gambia', 'Gambia','gmb', 0)
        , (268, 'GE', 'Georgia', 'Georgien','geo', 0)
        , (288, 'GH', 'Ghana', 'Ghana','gha', 0)
        , (292, 'GI', 'Gibraltar', 'Gibraltar','gib', 0)
        , (304, 'GL', 'Greenland', 'Grönland','grl', 0)
        , (308, 'GD', 'Grenada', 'Grenada','grd', 0)
        , (312, 'GP', 'Guadeloupe', 'Guadeloupe','glp', 0)
        , (316, 'GU', 'Guam', 'Guam','gum', 0)
        , (320, 'GT', 'Guatemala', 'Guatemala','gtm', 0)
        , (831, 'GG', 'Guernsey', 'Guernsey (Kanalinsel)','ggy', 0)
        , (324, 'GN', 'Guinea', 'Guinea','gin', 0)
        , (624, 'GW', 'Guinea-Bissau', 'Guinea-Bissau','gnb', 0)
        , (328, 'GY', 'Guyana', 'Guyana','guy', 0)
        , (332, 'HT', 'Haiti', 'Haiti','hti', 0)
        , (334, 'HM', 'Heard Island and McDonald Islands', 'Heard und McDonaldinseln','hmd', 0)
        , (336, 'VA', 'Holy See (Vatican City State)', 'Vatikanstadt','vat', 0)
        , (340, 'HN', 'Honduras', 'Honduras','hnd', 0)
        , (344, 'HK', 'Hong Kong', 'Hongkong','hkg', 0)
        , (356, 'IN', 'India', 'Indien','ind', 0)
        , (360, 'ID', 'Indonesia', 'Indonesien','idn', 0)
        , (364, 'IR', 'Iran, Islamic Republic of', 'Iran, Islamische Republik','irn', 0)
        , (368, 'IQ', 'Iraq', 'Irak','irq', 0)
        , (833, 'IM', 'Isle of Man', 'Insel Man','imn', 0)
        , (376, 'IL', 'Israel', 'Israel','isr', 0)
        , (388, 'JM', 'Jamaica', 'Jamaika','jam', 0)
        , (392, 'JP', 'Japan', 'Japan','jpn', 0)
        , (832, 'JE', 'Jersey', 'Jersey (Kanalinsel)','jey', 0)
        , (400, 'JO', 'Jordan', 'Jordanien','jor', 0)
        , (398, 'KZ', 'Kazakhstan', 'Kasachstan','kaz', 0)
        , (404, 'KE', 'Kenya', 'Kenia','ken', 0)
        , (296, 'KI', 'Kiribati', 'Kiribati','kir', 0)
        , (410, 'KR', 'Korea, Republic of', 'Korea, Republik (Südkorea)','kor', 0)
        , (414, 'KW', 'Kuwait', 'Kuwait','kwt', 0)
        , (417, 'KG', 'Kyrgyzstan', 'Kirgisistan','kgz', 0)
        , (422, 'LB', 'Lebanon', 'Libanon','lbn', 0)
        , (426, 'LS', 'Lesotho', 'Lesotho','lso', 0)
        , (430, 'LR', 'Liberia', 'Liberia','lbr', 0)
        , (434, 'LY', 'Libya', 'Libyen','lby', 0)
        , (438, 'LI', 'Liechtenstein', 'Liechtenstein','lie', 0)
        , (446, 'MO', 'Macao', 'Macao','mac', 0)
        , (807, 'MK', 'Macedonia, The Former Yugoslav Republic of', 'Mazedonien, ehem. jugoslawische Republik [2b]','mkd', 0)
        , (450, 'MG', 'Madagascar', 'Madagaskar','mdg', 0)
        , (454, 'MW', 'Malawi', 'Malawi','mwi', 0)
        , (458, 'MY', 'Malaysia', 'Malaysia','mys', 0)
        , (462, 'MV', 'Maldives', 'Malediven','mdv', 0)
        , (466, 'ML', 'Mali', 'Mali','mli', 0)
        , (584, 'MH', 'Marshall Islands', 'Marshallinseln','mhl', 0)
        , (474, 'MQ', 'Martinique', 'Martinique','mtq', 0)
        , (478, 'MR', 'Mauritania', 'Mauretanien','mrt', 0)
        , (480, 'MU', 'Mauritius', 'Mauritius','mus', 0)
        , (175, 'YT', 'Mayotte', 'Mayotte','myt', 0)
        , (484, 'MX', 'Mexico', 'Mexiko','mex', 0)
        , (583, 'FM', 'Micronesia, Federated States of', 'Mikronesien','fsm', 0)
        , (498, 'MD', 'Moldova, Republic of', 'Moldawien (Republik Moldau)','mda', 0)
        , (492, 'MC', 'Monaco', 'Monaco','mco', 0)
        , (496, 'MN', 'Mongolia', 'Mongolei','mng', 0)
        , (499, 'ME', 'Montenegro', 'Montenegro','mne', 0)
        , (500, 'MS', 'Montserrat', 'Montserrat','msr', 0)
        , (504, 'MA', 'Morocco', 'Marokko','mar', 0)
        , (508, 'MZ', 'Mozambique', 'Mosambik','moz', 0)
        , (104, 'MM', 'Myanmar', 'Burma (jetzt Myanmar)','mmr', 0)
        , (516, 'NA', 'Namibia', 'Namibia','nam', 0)
        , (520, 'NR', 'Nauru', 'Nauru','nru', 0)
        , (524, 'NP', 'Nepal', 'Nepal','npl', 0)
        , (540, 'NC', 'New Caledonia', 'Neukaledonien','ncl', 0)
        , (554, 'NZ', 'New Zealand', 'Neuseeland','nzl', 0)
        , (558, 'NI', 'Nicaragua', 'Nicaragua','nic', 0)
        , (562, 'NE', 'Niger', 'Niger','ner', 0)
        , (566, 'NG', 'Nigeria', 'Nigeria','nga', 0)
        , (570, 'NU', 'Niue', 'Niue','niu', 0)
        , (574, 'NF', 'Norfolk Island', 'Norfolkinsel','nfk', 0)
        , (580, 'MP', 'Northern Mariana Islands', 'Nördliche Marianen','mnp', 0)
        , (512, 'OM', 'Oman', 'Oman','omn', 0)
        , (586, 'PK', 'Pakistan', 'Pakistan','pak', 0)
        , (585, 'PW', 'Palau', 'Palau','plw', 0)
        , (275, 'PS', 'Palestinian Territory, Occupied', 'Palästinensische Autonomiegebiete','pse', 0)
        , (591, 'PA', 'Panama', 'Panama','pan', 0)
        , (598, 'PG', 'Papua New Guinea', 'Papua-Neuguinea','png', 0)
        , (600, 'PY', 'Paraguay', 'Paraguay','pry', 0)
        , (604, 'PE', 'Peru', 'Peru','per', 0)
        , (608, 'PH', 'Philippines', 'Philippinen','phl', 0)
        , (612, 'PN', 'Pitcairn', 'Pitcairninseln','pcn', 0)
        , (630, 'PR', 'Puerto Rico', 'Puerto Rico','pri', 0)
        , (634, 'QA', 'Qatar', 'Katar','qat', 0)
        , (638, 'RE', 'Réunion', 'Réunion','reu', 0)
        , (643, 'RU', 'Russian Federation', 'Russische Föderation','rus', 0)
        , (646, 'RW', 'Rwanda', 'Ruanda','rwa', 0)
        , (652, 'BL', 'Saint Barthélemy', 'Saint-Barthélemy','blm', 0)
        , (654, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'St. Helena','shn', 0)
        , (659, 'KN', 'Saint Kitts and Nevis', 'St. Kitts und Nevis','kna', 0)
        , (662, 'LC', 'Saint Lucia', 'St. Lucia','lca', 0)
        , (663, 'MF', 'Saint Martin (French part)', 'Saint-Martin (franz. Teil)','maf', 0)
        , (666, 'PM', 'Saint Pierre and Miquelon', 'Saint-Pierre und Miquelon','spm', 0)
        , (670, 'VC', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen','vct', 0)
        , (882, 'WS', 'Samoa', 'Samoa','wsm', 0)
        , (674, 'SM', 'San Marino', 'San Marino','smr', 0)
        , (678, 'ST', 'Sao Tome and Principe', 'São Tomé und Príncipe','stp', 0)
        , (682, 'SA', 'Saudi Arabia', 'Saudi-Arabien','sau', 0)
        , (686, 'SN', 'Senegal', 'Senegal','sen', 0)
        , (690, 'SC', 'Seychelles', 'Seychellen','syc', 0)
        , (694, 'SL', 'Sierra Leone', 'Sierra Leone','sle', 0)
        , (702, 'SG', 'Singapore', 'Singapur','sgp', 0)
        , (534, 'SX', 'Sint Maarten (Dutch part)', 'Sint Maarten (niederl. Teil)','sxm', 0)
        , (90, 'SB', 'Solomon Islands', 'Salomonen','slb', 0)
        , (706, 'SO', 'Somalia', 'Somalia','som', 0)
        , (239, 'GS', 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südlichen Sandwichinseln','sgs', 0)
        , (710, 'ZA', 'South Africa', 'Südafrika','zaf', 0)
        , (728, 'SS', 'South Sudan', 'Südsudan','ssd', 0)
        , (144, 'LK', 'Sri Lanka', 'Sri Lanka','lka', 0)
        , (729, 'SD', 'Sudan', 'Sudan','sdn', 0)
        , (740, 'SR', 'Suriname', 'Suriname','sur', 0)
        , (744, 'SJ', 'Svalbard and Jan Mayen', 'Svalbard und Jan Mayen','sjm', 0)
        , (748, 'SZ', 'Swaziland', 'Swasiland','swz', 0)
        , (760, 'SY', 'Syrian Arab Republic', 'Syrien, Arabische Republik','syr', 0)
        , (158, 'TW', 'Taiwan, Province of China', 'Republik China (Taiwan)','twn', 0)
        , (762, 'TJ', 'Tajikistan', 'Tadschikistan','tjk', 0)
        , (834, 'TZ', 'Tanzania, United Republic of', 'Tansania, Vereinigte Republik','tza', 0)
        , (764, 'TH', 'Thailand', 'Thailand','tha', 0)
        , (626, 'TL', 'Timor-Leste', 'Osttimor (Timor-Leste)','tls', 0)
        , (768, 'TG', 'Togo', 'Togo','tgo', 0)
        , (772, 'TK', 'Tokelau', 'Tokelau','tkl', 0)
        , (776, 'TO', 'Tonga', 'Tonga','ton', 0)
        , (780, 'TT', 'Trinidad and Tobago', 'Trinidad und Tobago','tto', 0)
        , (788, 'TN', 'Tunisia', 'Tunesien','tun', 0)
        , (792, 'TR', 'Turkey', 'Türkei','tur', 0)
        , (795, 'TM', 'Turkmenistan', 'Turkmenistan','tkm', 0)
        , (796, 'TC', 'Turks and Caicos Islands', 'Turks- und Caicosinseln','tca', 0)
        , (798, 'TV', 'Tuvalu', 'Tuvalu','tuv', 0)
        , (800, 'UG', 'Uganda', 'Uganda','uga', 0)
        , (804, 'UA', 'Ukraine', 'Ukraine','ukr', 0)
        , (581, 'UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands','umi', 0)
        , (784, 'AE', 'United Arab Emirates', 'Vereinigte Arabische Emirate','are', 0)
        , (840, 'US', 'United States', 'Vereinigte Staaten von Amerika','usa', 0)
        , (858, 'UY', 'Uruguay', 'Uruguay','ury', 0)
        , (860, 'UZ', 'Uzbekistan', 'Usbekistan','uzb', 0)
        , (548, 'VU', 'Vanuatu', 'Vanuatu','vut', 0)
        , (862, 'VE', 'Venezuela, Bolivarian Republic of', 'Venezuela','ven', 0)
        , (704, 'VN', 'Viet Nam', 'Vietnam','vnm', 0)
        , (92, 'VG', 'Virgin Islands, British', 'Britische Jungferninseln','vgb', 0)
        , (850, 'VI', 'Virgin Islands, U.S.', 'Amerikanische Jungferninseln','vir', 0)
        , (876, 'WF', 'Wallis and Futuna', 'Wallis und Futuna','wlf', 0)
        , (732, 'EH', 'Western Sahara', 'Westsahara','esh', 0)
        , (887, 'YE', 'Yemen', 'Jemen','yem', 0)
        , (894, 'ZM', 'Zambia', 'Sambia','zmb', 0)
        , (716, 'ZW', 'Zimbabwe', 'Simbabwe','zwe', 0)
        , (384, 'CI', "Côte d'Ivoire", "Côte d’Ivoire (Elfenbeinküste)", 'civ', 0)
        , (408, 'KP', "Korea, Democratic People's Republic of", "Korea, Demokratische Volksrepublik (Nordkorea)", 'prk', 0)
        , (418, 'LA', "Lao People's Democratic Republic", "Laos, Demokratische Volksrepublik",'lao', 0)
    ]
